### ISSUE TITLE
Hi! how I can see the demo?

### ISSUE THREAD

**Issue by peteralexandercharles** [imagineai/create-django-app#3]
(newspaper) peter@pop-os:~/Desktop/learn-django/django-app$ imagine demo django-app
 ›   Error: 
 ›
 ›   SE000045 => Your object API "album-api-fetch-update" has an
 ›    update action, so you have to specify a primary key and at
 ›    least one field.. At django-app:104:1
 ›     104 ┃ API album-api-fetch-update {
 ›   105 ┃     model        Album
 ›   106 ┃     actions      [Read,ReadMany,Update]
 ›   107 ┃     permissions  [permission-1]
 ›   108 ┃     filter       [name,num_stars]
 ›   109 ┃     data         [name,songs]
 ›   110 ┃ }

**Comment by anusheel** [comment]
Hi - can you try `imagine demo` command and select Django as the framework and one of the 2 available demos. 

This is what you will see
```
$ imagine demo
? Please select the framework for which you would like to run the demo: django
? Please select which demo app you would like to run: Santa Planner
51 files written
You have successfully installed the demo-app!
Now you can run "cd santaplanner && make install && make run" to install the dependencies and open a web server running at
http://127.0.0.1:8000/demo/
```

**Comment by anusheel** [comment]
Hi @peteralexandercharles let us know if that worked? Happy to help debug any errors here. We are always here to help

**Comment by peteralexandercharles** [comment]
Perfect! Thank you very much!
